name: FasterCart
version: '${project.version}'
main: me.lia_lv.fastercart.FasterCart
api-version: '1.13'
permissions:
  fastercart.command:
    default: true
commands:
  fastercart:
    description: FasterCart Core Command
    aliases:
      - fc